version: '3'
services:
  copplay-cloud-mysql:
#    build:
#      context: docs/db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    container_name: copplay-cloud-mysql
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - spring_cloud_default

  copplay-cloud-redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    container_name: copplay-cloud-redis
    hostname: copplay-cloud-redis
    networks:
      - spring_cloud_default

#  copplay-cloud-register:
#    build:
#      context: ./copplay-cloud-register
#    restart: always
#    ports:
#      - 8848:8848
#      - 9848:9848
#    container_name: copplay-cloud-register
#    hostname: copplay-cloud-register
#    image: copplay-cloud-register
#    networks:
#      - spring_cloud_default
#
#  copplay-cloud-router:
#    build:
#      context: ./copplay-cloud-router
#    restart: always
#    ports:
#      - 9999:9999
#    container_name: copplay-cloud-router
#    hostname: copplay-cloud-router
#    image: copplay-cloud-router
#    networks:
#      - spring_cloud_default

networks:
  spring_cloud_default:
    driver: bridge
